In [1]:
import numpy as np
import matplotlib.pyplot as pp


In [2]:
# Task A: Create Gaus Solver and test with given values

A = np.array([[8, -2, 1, 3],
    [1, -5, 2, 1],
    [-1, 2, 7, 2],
    [2, -1, 3, 8],])



b = np.array([[9],
    [-7],
    [-1],
    [5],])

A.astype(float)
b.astype(float)

array([[ 9.],
       [-7.],
       [-1.],
       [ 5.]])

In [3]:
def MyGauss(Am, bv):
    #get the dimension of the matrix
    
    
    # convert the matrices to float typed matrices
    A = np.copy(Am).astype(np.float32)
    b = np.copy(bv).astype(np.float32)
    n = len(A)
    

    
    print(A)
    print(b)
    
    
    
    
    
    # use pivots to eliminate Xn from the other rows
    for i in range(0, n-1):# i goes from first column to the column before the last
        for j in range(i+1,n):
            ratio = A[j,i]/A[i,i]
            print(A[j,i], A[i,i])
            A[j] = A[j] - (ratio * A[i])
            b[j] = b[j] - (ratio * b[i])
            
        
                           
    
    print("")
    print("Final A:") 
    print(A)
    print("Final B")
    print(b)
    
    
    x = np.zeros((n,1))
    
    for k in range(n-1,-1,-1): # say i start with k = 3 , i.e. 4th row
        xv = b[k]/A[k,k] # xvalue = b[3]/A[3,3]
        for l in range(k+1,n): # so 4 to 4
            xv -= A[k,l]/A[k,k]* x[l] # subtract all upper x values 
        x[k] = xv
    
    print("x values are: ")
    print(x)
    

    
    

In [4]:
MyGauss(A, b)



[[ 8. -2.  1.  3.]
 [ 1. -5.  2.  1.]
 [-1.  2.  7.  2.]
 [ 2. -1.  3.  8.]]
[[ 9.]
 [-7.]
 [-1.]
 [ 5.]]
1.0 8.0
-1.0 8.0
2.0 8.0
1.75 -4.75
-0.5 -4.75
2.5526316 7.815789

Final A:
[[ 8.        -2.         1.         3.       ]
 [ 0.        -4.75       1.875      0.625    ]
 [ 0.         0.         7.815789   2.6052632]
 [ 0.         0.         0.         6.333333 ]]
Final B
[[ 9.       ]
 [-8.125    ]
 [-2.868421 ]
 [ 4.5420876]]
x values are: 
[[ 1.32323241]
 [ 1.56565666]
 [-0.60606062]
 [ 0.71717173]]


In [5]:
A.astype(float)
A.dtype

dtype('int32')

In [6]:
A.astype(np.float32)

array([[ 8., -2.,  1.,  3.],
       [ 1., -5.,  2.,  1.],
       [-1.,  2.,  7.,  2.],
       [ 2., -1.,  3.,  8.]], dtype=float32)

In [7]:
for l in range(0,0):
    print(l)

In [8]:
#Task 2

In [9]:
#Task 3

currents = np.array([[0,-1,-1,0,0,0]
                    ,[0,1,0,-1,-1,0]
                    ,[0,0,1,1,0,-1]
                    ,[0,-1,-2,-1,0,0]
                    ,[0,0,0,-1,2,-1]
                    ,[1,0,0,0,-1,-1]])

results = np.array([
    [0],
    [0],
    [0],
    [0],
    [0],
    [0]])

MyGauss(currents,results)

[[ 0. -1. -1.  0.  0.  0.]
 [ 0.  1.  0. -1. -1.  0.]
 [ 0.  0.  1.  1.  0. -1.]
 [ 0. -1. -2. -1.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 1.  0.  0.  0. -1. -1.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
1.0 0.0
nan nan
nan nan
nan nan
inf nan
nan nan
nan nan
nan nan
nan nan
nan nan
nan nan

Final A:
[[ 0. -1. -1.  0.  0.  0.]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]]
Final B
[[ 0.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
x values are: 
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


<ipython-input-3-d8b642d7ce72>:22: RuntimeWarning: invalid value encountered in float_scalars
  ratio = A[j,i]/A[i,i]
<ipython-input-3-d8b642d7ce72>:22: RuntimeWarning: divide by zero encountered in float_scalars
  ratio = A[j,i]/A[i,i]
<ipython-input-3-d8b642d7ce72>:24: RuntimeWarning: invalid value encountered in multiply
  A[j] = A[j] - (ratio * A[i])
<ipython-input-3-d8b642d7ce72>:25: RuntimeWarning: invalid value encountered in multiply
  b[j] = b[j] - (ratio * b[i])
<ipython-input-3-d8b642d7ce72>:40: RuntimeWarning: invalid value encountered in true_divide
  xv = b[k]/A[k,k] # xvalue = b[3]/A[3,3]
<ipython-input-3-d8b642d7ce72>:42: RuntimeWarning: divide by zero encountered in float_scalars
  xv -= A[k,l]/A[k,k]* x[l] # subtract all upper x values
<ipython-input-3-d8b642d7ce72>:42: RuntimeWarning: invalid value encountered in float_scalars
  xv -= A[k,l]/A[k,k]* x[l] # subtract all upper x values
